### DISCUSSION TITLE
Newlines not preserved, nonbreaking spaces added

### DISCUSSION THREAD

**Discussion by fred-apex-ai** [erebe/greenclip#156] [Q&A]
When I copy multi-line text, and I paste it, the newlines are preserved.

When I use greenclip v4.2 to select some entry from the list, it removes the newlines, which make it unusable. I didn't have this behavior on my previous laptop. I am using greenclip v4.2, which is around for a while so I think I had been using the same version on my previous laptop.

I am using greenclip with ilia on Regolith 3. Previously I used greenclip with rofi, which worked flawlessly. 

I wonder where a difference in behavior could come from? Any pointers are appreciated.

Here is my i3 config snippet 
```
set $greenclip /home/frederik.beaujean/.local/bin/greenclip
exec --no-startup-id $greenclip daemon
## Launch // clipboard selection // <><Enter>
# copy to primary selection and clipboard. Install moreutils for `ifne` that prevents emptying the selection when nothing comes out of ilia
bindsym $mod+Return exec $greenclip print | ilia -p textlist -n | ifne xclip -i -sel clipboard -f | ifne  xclip -i -sel primary
```

To understand what happens, I tried greenclip in the terminal w/o ilia. When I copy the snippet above, multiple lines are joined together. 

```
❱ greenclip print | batt
       │ STDIN
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ set $greenclip /home/frederik.beaujean/.local/bin/greenclip exec --no-startup-id $greenclip daemon ## Launch // clipboard selection // <><Enter> # copy to prima
       │ ry selection and clipboard. Install moreutils for `ifne` that prevents emptying the selection when nothing comes out of ilia bindsym $mod+Return exec $greenclip 
       │ print | ilia -p textlist -n | ifne xclip -i -sel clipboard -f | ifne  xclip -i -sel primary 
```

Here is my `greenclip.toml`:

```toml
[greenclip]
  blacklisted_applications = []
  enable_image_support = false
  history_file = "/home/frederik.beaujean/.cache/greenclip.history"
  static_history = []
  image_cache_directory = "/tmp/greenclip"
  max_history_length = 100
  max_selection_size_bytes = 0
  trim_space_from_selection = false
  use_primary_selection_as_input = false
```
I played with the config toggling `trim_space_from_selection` didn't make a difference
