### DISCUSSION TITLE
It is not working

### DISCUSSION THREAD

**Discussion by FerrielMelarpis** [erebe/greenclip#159] [Q&A]
I installed greenclip and rofi-greenclip but I can't get it to work. It doesn't put the selected or yanked items in its history.
Here is my config:
```toml
[greenclip]
  history_file = "$HOME/.cache/greenclip.history"
  max_history_length = 50
  max_selection_size_bytes = 0
  trim_space_from_selection = true
  use_primary_selection_as_input = true
  blacklisted_applications = []
  enable_image_support = true
  image_cache_directory = "/tmp/greenclip"
  static_history = []
```
I tried running `pkill greenclip && greenclip clear && greenclip daemon &` to restart the daemon but did not work as well. `greenclip print` shows nothing.
