### ISSUE TITLE
feature request: support named entry for history

### ISSUE THREAD

**Issue by jeffrey4l** [erebe/greenclip#148]
when the line is lone enought or some random string, it is hard to remember the text, especially for static_history.

Could we support a named static history, and can suport search based on name and copy the value only

for example

```toml
[greeclip.static_named_history]
personal_ssh_key = "ssh-rsa xxxx"
company_ssh_key = "ssh-rsa yyyy"
```
